config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :categories
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :category_id, :title, :content, presence: true
  belongs_to :category
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order("created_at DESC")
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_categories

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = set_post
  end

  def update
    set_post
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :photo)
  end

  def set_categories
    @categories = Category.all.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/line" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<%= render "shared/line" %>
<%= render "shared/home-cards" %>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="mb-5 mt-5">Manage your Blog</h1>
      <%= render "shared/form" %>
      <%= link_to "Delete this blog", post_path(@post), class: "btn btn-link mb-5 row row-cols-auto", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?" } %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1 class="mt-5 mb-3">Blog Index</h1>
    <h2>Posts</h2>
      <div class="cards">
        <div class="row cards-space">
          <% @posts.each_with_index do |post, key| %>
            <div class="card col-sm-12 col-lg-3 p-0">
              <%= cl_image_tag post.photo.key, class: "card-imgs" %>
              <div class="category-section">
                <h4><%= post.category.name %></h4>
              </div>
              <%= link_to post_path(post) do %>
              <div class="card-underline">
                <h5 class="card-title ms-3 mt-3"><strong><%= post.title %></strong></h5>
              <% end %>
              </div>
              <p class="card-content ms-3">
              <%= post.content ? post.content.truncate(35) : "" %>
              </p>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>
    <%= render 'shared/form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="title mt-5">
    <h1><strong><%= @post.title %></strong></h1>
  </div>
  <%= render "shared/line" %>
  <div class="blog-photo mt-4 mb-4">
    <%= cl_image_tag @post.photo.key, crop: :mfit %>
  </div>
  <%= render "shared/line" %>
      <%= @post.category.name %>
      <%= link_to "Edit", edit_post_path(@post)  %>
  <div class="content mt-5">
      <p><%= @post.content %></p>
  </div>
</div>

app/views/shared/_banner.html.erb
<section class="banner mb-3">
  <div class="banner-image">
      <div class="container">
        <div class="banner-content">
          <h1 class="banner-title mb-4">WELCOME TO MY BLOG</h1>
            <p class="banner-text mb-5">I do a little bit of everything, ranging from coding and marketing to music and photography. Here you will find my collection of random skills and travel experiences.</p>
            <a class="btn btn-primary" href="/posts">Get Started</a>
        </div>
      </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-white mt-5">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/samdungedup/" target="_blank" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/samdu-ngedup-8b8a1296/" target="_blank" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/samdungedup" target="_blank" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <p class="text-white" target="_blank">© 2023 Copyright: Samdu Ngedup</p>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_form.html.erb
<div class="form">
  <%= simple_form_for @post do |f| %>
    <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    <%= f.input :photo, as: :file %>
    <%= f.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})%><br>
    <%= f.button :submit, 'Confirm', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_home-cards.html.erb
<section class="photos">
  <div class="container">
    <div class="wrapper">
    <div class="category mb-4">
      <h2>CATEGORIES</h2>
    </div>
      <div class="mb-3"><%= render "shared/line" %></div>
      <figure>
        <div class="post-image btn-container"><%= image_tag "web.jpg", class: "h-100" %><button class="btn btn-primary child">CODING</button></div>
        <div class="post-image btn-container"><%= image_tag "walk.jpg", class: "h-100" %><button class="btn btn-primary child">TRAVEL</button></div>
      </figure>
      <!-- triple image row-->
      <figure>
        <div class="post-image btn-container"><%= image_tag "product.jpg", class: "h-100" %><button class="btn btn-primary child">MISCELLANEOUS</button></div>
        <div class="post-image btn-container"><%= image_tag "sunset.jpg", class: "h-100" %><button class="btn btn-primary child">PHOTOGRAPHY</button></div>
        <div class="post-image btn-container"><%= image_tag "music.jpg", class: "h-100" %><button class="btn btn-primary child">MUSIC</button></div>
      </figure>
    </div>
  </div>
</section>

app/views/shared/_line.html.erb
<div class="line"></div>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", class: "logo" %>
    <% end %>
    <nav>
      <ul class="mt-3" id="menuList">
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "About", posts_path %></li>
      </ul>
    </nav>
    <img src="https://raw.githubusercontent.com/samdungedup/blog/07d5d3eeaeee0d336efd73ec48495c919d67bcdf/app/assets/images/menu.svg" onclick="toggleMenu()" class= "menu-icon">
  </div>
</div>

<script>

  var menuList = document.getElementById("menuList");

  menuList.style.maxHeight = "0px";

  function toggleMenu(){

    if(menuList.style.maxHeight == "0px")
      {
        menuList.style.maxHeight = "130px";
      }
    else
      {
        menuList.style.maxHeight = "0px";
      }
  }

  </script>

app/views/shared/_test2.html.erb
<section class="photos">
  <div class="container">
    <div class="wrapper">
      <!-- single image row
      <figure>
        <div class="post-image"><%= image_tag "photography.jpg", class: "h-100" %></div>
      </figure>
      double image row-->
      <figure>
        <div class="post-image btn-container"><%= image_tag "web.jpg", class: "h-100" %><button class="btn btn-primary child">CODING</button></div>
        <div class="post-image btn-container"><%= image_tag "walk.jpg", class: "h-100" %><button class="btn btn-primary child">TRAVEL</button></div>
      </figure>
      <!-- triple image row-->
      <figure>
        <div class="post-image btn-container"><%= image_tag "product.jpg", class: "h-100" %><button class="btn btn-primary child">MISCELLANEOUS</button></div>
        <div class="post-image btn-container"><%= image_tag "sunset.jpg", class: "h-100" %><button class="btn btn-primary child">PHOTOGRAPHY</button></div>
        <div class="post-image btn-container"><%= image_tag "music.jpg", class: "h-100" %><button class="btn btn-primary child">MUSIC</button></div>
      </figure>
    </div>
  </div>
</section>